### PR TITLE
Don't show buy button on own listings

### PR DESCRIPTION
**Pull request by Libter**

### CODE REVIEW

**Comment by jjeffryes** [comment]
@morebrownies we decided to leave the buy button visible on your own products on purpose. Do you think it should be removed? 

Or maybe it should just be disabled, and show a tooltip on hover saying you can't buy your own product?

I think there is some value in letting a seller see the purchase flow, but we leave the buy button active, we should block the purchase button, so they don't get the error message that it currently shows when you try to buy your own product.

**Comment by ghost** [comment]
I have a suggestion for this on #1399 Sellers editing listing settings on listing page.

**Comment by morebrownies** [comment]
Yes we want to allow the vendor to see their own checkout process since it comes with a number of benefits:

1) They can double check to see which moderators are showing up
2) They can test their color choices to make sure they're rending ok 
3) They can also see shipping prices display in real time

**Comment by jjeffryes** [comment]
We want to keep the buy button visible, so I'm going to close this.

A better solution would be to deactivate the purchase button if it's your own listing, rather than show an error message.

**Pull request closed without merging**
