### PR TITLE
Finish Slovak translation

### PR DESCRIPTION
**Pull request by mariodian**
Finished the remaining Slovak translation.

### CODE REVIEW

**Comment by mariodian** [comment]
Sorry the object wasn't closed properly, I guess it got there during merging.

**Comment by MilosMosovsky** [comment]
@mariodian next time it is better to use `git commit --fixup sha1` 
[https://robots.thoughtbot.com/autosquashing-git-commits](https://robots.thoughtbot.com/autosquashing-git-commits)
[http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html) :)

**Comment by mariodian** [comment]
@MilosMosovsky thanks. I'm fairly stupid when it comes to git.

**Comment by MilosMosovsky** [comment]
@mariodian do you mind if i squash commits to 1 single commit ? It should not be merged in 4 commits

**Comment by mariodian** [comment]
@MilosMosovsky sure go ahead. Thanks.

**Comment by mariodian** [comment]
Thank's I'll fix it.

**Pull request merged**
