### PR TITLE
Make various headings non-selectable

### PR DESCRIPTION
**Pull request by JustinDrake**

### CODE REVIEW

**Comment by jjeffryes** [comment]
What issue is this addressing? Do you mean selectable as in the user can select the text?

**Comment by JustinDrake** [comment]
@jjeffryes: Yes, selectable as in the user can select the text. For example, if you go in "Settings", then the "Settings" text label itself ought not be selectable. It's just a minor polish to please the user.

**Comment by jjeffryes** [comment]
Why would the user not want to be able to select text? That's normal behavior in a web app. 

I'm not opposed to the change, I just want to understand what the thinking behind it is before we remove expected functionality.

**Comment by JustinDrake** [comment]
@jjeffryes: This is not a standard webapp. It doesn't run in a standard browser, and it has the feel of a native app. Native apps do not have selectable headings. At least that's not the standard UX.

**Comment by jjeffryes** [comment]
That's a valid point.

I'll close this PR, can you redo it so all h tags are non-selectable, and then re-open the PR?

Make sure it's on the h tags only, and not the .h1, .h2 etc. classes (those are used to make non-headline elements the same style as headlnes). 

There shouldn't be a situation were we need a h tag to be selectable.

**Pull request closed without merging**
