### PR TITLE
Made "does not ship to you" less intrusive

### PR DESCRIPTION
**Pull request by morebrownies**
Let's see how this feels, it's much more minimal now.

### CODE REVIEW

**Comment by jjeffryes** [comment]
@morebrownies I think we'll need the icon to be bigger, or use another icon. On my smaller screen the anti-aliasing turns it into a solid white circle. 

image

**Comment by morebrownies** [comment]
@jjeffryes I just pushed an update, let me know if this resolves your issue.

**Comment by morebrownies** [comment]
Re-ordered the Clear conversation link based on feedback:

> vintagefashionbazaar [7:26 AM] 
> Just accidently Blocked someone when trying to clear conversation.
> 
> i think Block, should be top of the list. and NOT next to "clear Conversation" way too easy to block people accidentally.

**Comment by jjeffryes** [comment]
That looks better, but they're slightly off center now. I'll look at the css and see what I can do.

**Pull request merged**
