### PR TITLE
Add translations & more

### PR DESCRIPTION
**Pull request by Kirvx**
- Add translations
- Move most of the punctuations in the en-US.json file
- Delete a few unnecessary " : " (it's more pleasant for reading)
- Increase size of "Highlight text to style"

**And few cosmetic changes:**
## Before/After:

Thoughts?

### CODE REVIEW

**Comment by jjeffryes** [comment]
That might be a bit too much space, and I'm not sure about the arrow icons.

@morebrownies what do you think?

**Comment by morebrownies** [comment]
Yeah, I'm not crazy about the arrows either. Mainly because it seems a bit odd to put icons in between the text and it breaks some patterns we've set throughout the app. 

Also, I'll clean up typography/spacing in the Settings > Store tab on the branch I'm currently working on.

**Comment by Kirvx** [comment]
Ok I close this one, and will make another pull request for translations update only.

**Comment by morebrownies** [comment]
Thanks @Kirvx

**Pull request closed without merging**
