### PR TITLE
Optimize jQuery selectors

### PR DESCRIPTION
**Pull request by mariodian**
I did a little optimization of jQuery selectors.

Mostly changing `$('.parent .child')` to `$('.parent').find('.child')` which is [way faster](http://stackoverflow.com/a/18222210).

I also put some selectors into variables if they're used numerous times inside a method. That way jQuery doesn't have to access DOM every time it needs to use the element. 

I think we should stick to .find() in the future for the performance reasons.

### CODE REVIEW

**Comment by rmisio** [comment]
Could you please link to some documentation that shows that this approach is actually faster? You're turning one DOM query into two, so on the surface it doesn't seem like it would be faster.

I do agree we should be caching frequently used selectors.

**Comment by jjeffryes** [comment]
The jQuery site seems to say find is faster than using several classes as a selector. https://learn.jquery.com/performance/optimize-selectors/

**Comment by mariodian** [comment]
Thanks, I didn't know jQuery mentioned it. Anyway there are lot of perf tests available on the internet that prove so. Unfortunately jsperf.com has been down for a while.

**Comment by rmisio** [comment]
@jjeffryes where do you see that? The only thing I see regarding find says it's a good bet to use find if the first element is an id, because then `document.getElementById()` can be used which is faster than `document.querySelectorAll()`. It also says "although the speed improvement may be diminished by the subsequent call to .find()".

**Comment by jjeffryes** [comment]
I'm guessing based on what they say there. Each element in the selector uses querySelectorAll, my assumption is (.foo .bar .bat) would scan the entire document for bat, then scan all of bat's ancestors for bar, then all of bar's ancestors for foo. 

(.foo).find(.bar).find(.bat) would be faster in theory in that it does one DOM scan for foo, then only scans foo's descendants for bar, and bar's descendants for bat. 

But it would be good to have a test for it. That should be doable with the Web Dev tools, just run the same views in master and this branch, and check the render speed.

**Comment by rmisio** [comment]
whole lotta assumptions there :)

the jQuery docs is only specifically talking about if the first element in the selector is an id.

Same goes for the jsPerf link that @mariodian provided. It is targeting the first element with an id.

**Comment by rmisio** [comment]
Believe, I'm all for optimization. But, I've yet to see any evidence / documentation that `$('.foo').find('.bar .baz')` is any faster than `$('.foo .bar .baz')`.

**Comment by jjeffryes** [comment]
I ran the Discover and User pages in master and this branch five times each, the scripting time for Discover was only 0.48ms faster on average, and the User page was 3.64ms faster on average.

That's not conclusive (the numbers for both bounced up and down), but I do think it indicates this kind of optimization doesn't have a large impact. As the doc I linked to pointed out, most of the time selector optimization isn't needed. 

I think caching elements that are used more than once, and using find on any selector that starts with an ID would be good.

**Comment by rmisio** [comment]
I agree with your last statement.

FWIW, I don't think the test on the User page is valid because a dom selector was cached as part of the update, which we all seem to agree is a valid optimization.

The true test for the point up for debate would be to do a jsPerf type check (site is down...) on strictly the `$('.foo .bar .baz)` vs. `$('.foo').find('.bar .baz')`.

**Comment by jjeffryes** [comment]
My point was with all the optimizations, the difference was still pretty minimal. 

I looked, I couldn't find anything like jsPerf available. We'd have to write our own tests if we were serious about it. 

(and seriously, a 3 ms difference isn't enough we should worry about debating it)

**Comment by mariodian** [comment]
You can have a look at [this post](http://stackoverflow.com/posts/27268165/revisions). He made some basic test code. On chrome, find() performs better than anything else. Not sure about chained find() though, we'll have to wait until jsperf is online again.

I think even "3ms" for each "poorly" written selector can make a difference overall. The code will be huge in the future so I think we should start writing it as best as possible (if it's proven chained find() performs better).

**Comment by jjeffryes** [comment]
3ms total, for all optimizations made on pagenav and userPage combined. My feeling is using find doesn't make any difference unless there's an ID involved. 

For now, I think we should only use find on selectors that start with an ID, and just use multiple classes the rest of the time.

**Comment by rmisio** [comment]
yeah, let's wait for the proof re: multiple classes. My concern is that the chained find on those is slower, since it involves two DOM queries (both using querySelectorAll() behind the scenes). So, if "3ms" is important, we wouldn't want to add 3ms to the total (and i think it could be more than 3ms, since I don't think Josh's test focused on the specific issue at hand).

**Pull request merged**
