### PR TITLE
Shapeshift integration with Shifty Button

### PR DESCRIPTION
**Pull request by hoffmabc**
Ok this needs some testing, but worked fine for me. It basically allows altcoin payment through Shapeshift and their shifty button. 

Looks like this:

image

### CODE REVIEW

**Comment by hoffmabc** [comment]
We will need to find a place on the Purchases screen for this though.

**Comment by jjeffryes** [comment]
This also needs to be added to the same screen in the transaction modal, so people that don't pay right away can use it.

**Comment by hoffmabc** [comment]
That's what I mean above with the Purchases page.

**Comment by morebrownies** [comment]
I found a UX issue we're going to need to think through. 

We currently ask first time users to enter their Bitcoin Address (as pictured below). This could present issues for people that only use alt coins. They'll first need to setup a Bitcoin wallet, even if they're not using it. Not sure how much friction that will create, but definitely not ideal.

@jjeffryes heads up, we also need to remove the link on that screen for creating a temporary address, since Rush Wallet is closing. I think someone else brought that up today too.

**Comment by morebrownies** [comment]
screenshot 2016-11-28 17 42 30

**Comment by jjeffryes** [comment]
Altcoin users will still need to put in a btc address, otherwise they can't get a refund or have a dispute settled in their favor.

The link to the Rush wallet was removed in PR #1845

**Comment by jjeffryes** [comment]
Oops. Wrong button.

**Comment by morebrownies** [comment]
Ok. The experience will improve in 2.0 with the built in wallet.

**Comment by jjeffryes** [comment]
We could potentially add shapeshift into the refund and dispute resolution screens, but we'd need a way to save the fact that the user in question wants to be paid in alt coins, and which alt coin it was. 

The built-in wallet in 2.0 should make it simpler, since anyone that wants alt coins would presumably just sent btc from their internal wallet to shapeshift. If this functionality works out in 1.0, we could consider adding a "send money to alt coins" option in the wallet.

**Comment by ShapeShiftEmily** [comment]
Hey, @hoffmabc ! Please let us know if we can do any cross-marketing once you guys feel good with the integration. We are so excited to see this!

emily@shapeshift.io or on Skype @ ShapeShiftEmily

Also, we can get you guys set up with the affiliate program for monthly payouts if you would like to do that as well. Just get in touch!

**Pull request merged**
