### PR TITLE
Adds a Back To Top button to the Discover and User pages

### LINKED ISSUE #1536: In Discover, add a button to go back to the top of the page easily.
**Description**

Scrolling for a while leaves you pretty far down the page and requires a lot of scrolling to get back to the top. We should make it easier for the user by conditionally displaying a "Back to top" button when they scroll past a certain point.

**Requirements**
- [ ] Display a back to top button after the user scrolls beyond the default viewport. (#1)
- [ ] If the user scrolls back to the top or clicks "Back to top" hide the "Back to top" button. (#2)
- [ ] Also put button on store page.
- [ ] Only show button after the user scrolls far enough the top controls aren't visible (roughly one flick of the scroll wheel).
- [ ] Cool fade in effect.

### PR DESCRIPTION
**Pull request by rmisio**
closes #1536

### CODE REVIEW

**Comment by jjeffryes** [comment]
@morebrownies I think you'll want to do a styling pass on this one before we merge it

**Comment by morebrownies** [comment]
Will take a look soon

**Comment by morebrownies** [comment]
@rmisio there's an issue with chat completely covering the "Back to top" button when the chat panel is open. I created the btt branch last week that put the button on the left side to avoid this problem.

I'm fine with having the button on the right side, but we need to make sure it's always accessible.

**Comment by rmisio** [comment]
@morebrownies Not familiar with that branch, but I have no problems with it being on the left. If that's easier, we could do that. Otherwise, I'll have to give it the same treatment as the loading spinners, where it adjusts it's position based on the state of the chat app.

Let me know you're preference - the latter is a bit more work, but not a lot at all.

**Comment by morebrownies** [comment]
Let's go with the latter. If it starts to cover too much content and people complain about it, we can then move it to the left side, but I think it should be fine.

**Comment by jjeffryes** [comment]
Currently, the back to top gets covered by the chat app when it's opened. 

That would probably be fixed if this was updated with the positioning PR. 

Should the button be the so close to the same color as the background of the discover section? The two blues blend together when I look at them.

**Comment by rmisio** [comment]
@jjeffryes great screenshot!

**Comment by jjeffryes** [comment]
Yeah, wrong window had focus.

**Comment by jjeffryes** [comment]
Let's try this screenshot instead. 
image

**Comment by morebrownies** [comment]
We can use #252525 as the background of the button to solve the blending issue

**Comment by rmisio** [comment]
This should be ready to go - updated the color of the button + adjusting its positioning when chat is open.

**Pull request merged**
