### PR TITLE
Add german translation

### PR DESCRIPTION
**Pull request by z3ntu**

### CODE REVIEW

**Comment by jjeffryes** [comment]
This branch has merge conflicts, can you resolve those and commit the fix?

**Comment by z3ntu** [comment]
Is probably is because of the spanish remove-and-readd stuff but I don't know how to resolve this. I tried it via git clone and edit it, but it replaced the spanish characters with the question mark characters. Then I copied just the german translation and pasted it into the online editor and thats whats in the commit here...

**Comment by hoffmabc** [comment]
Need to make sure not to mess up the encoding of the file when editing it.

**Comment by z3ntu** [comment]
And how do I do that? :smiley:

**Comment by gubatron** [comment]
try not to use any weird encoding, since this stuff is rendered in HTML the safest way to do this is using HTML escape caracters. In spanish I removed all possible encoded characters and replaced them:

e.g.

`á` -> `HTML(&aacute;)`

(and if encoding must be used, make sure to save using utf-8)

**Comment by gubatron** [comment]
screen shot 2015-11-18 at 7 20 04 pm

**Pull request closed without merging**
