### PR TITLE
Add german translation (fixed, hopefully)

### PR DESCRIPTION
**Pull request by z3ntu**
This file was saved in UTF-8 (according to the program "WebStorm"), so there should be no problem...
Also some spanish characters are still as characters... like ó , á

### CODE REVIEW

**Comment by gubatron** [comment]
#LGTM

**Comment by gubatron** [comment]
thanks for using HTML codes in german

**Comment by gubatron** [comment]
can I merge this so I can continue the work in spanish?

**Comment by z3ntu** [comment]
of course

**Comment by z3ntu** [comment]
btw where do you choose the language for the client?

**Comment by hoffmabc** [comment]
/js/userMd.js

**Comment by jjeffryes** [comment]
We just updated the client so that when you load it the first time you'll go through an onboarding process, in the first step of that you choose your language.

**Pull request merged**
