### PR TITLE
[TESTING] Better trade flow

### PR DESCRIPTION
**Pull request by morebrownies**
**Changes**
- If store has no moderators, hide the moderated transaction type
- Added the "Do you have a bitcoin wallet?" step
- If the user already has a bitcoin return address, auto skip the step above
- Added the "Create a Wallet" step
- Modified the "Bitcoin return address" step
- Modified the "Payment type" screen
- Added all the Wallet provider icons
- Randomize the list of wallet providers

**Bugs**
- If you select a moderator and then select direct payment, the selected moderator still persists.

### CODE REVIEW

**Comment by SamPatt** [comment]
> Only use for microtransactions or when purchasing from a trusted seller.

I would change to "small purchases" since microtransactions usually refer to just cents, and that's not what we're trying to get across.

**Comment by SamPatt** [comment]
Hovering over the ? next to dispute fee explanation in the moderators payment flow shows a tooltip but only the first part can be viewed:

image

**Comment by SamPatt** [comment]
After erasing my bitcoin address in settings, and selecting "Yes" when it asks me if I have a Bitcoin wallet, it doesn't let me progress past this screen:

image

**Comment by morebrownies** [comment]
@SamPatt Hovering over the ? next to dispute fee explanation in the moderators payment flow shows a tooltip but only the first part can be viewed: should be fixed now

**Comment by morebrownies** [comment]
I would change to "small purchases" since microtransactions usually refer to just cents, and that's not what we're trying to get across. 

Good call, changed.

**Pull request merged**
