### PR TITLE
Improved contract page with image zoom

### PR DESCRIPTION
**Pull request by morebrownies**
**Changes**
- Cleaned up the contract detail page
- Output keywords 
- If the length of the keyword is greater than 100, i'm not outputting it on the page (people had novels set as keywords and it broke the page)
- Free shipping now shows on the contract detail page (if free shipping exists)
- Added image zoom on contract detail screen
- I output the category in the breadcrumb 
- If more than 5 photos on contract detail page, it truncates them and shows "view all"

**Bugs**
- Compression and size on contract photos seems over aggressive. Image zoom isn't really useful right now because of this. 
- Image overlay covers chat (can log this as a bug and come back to it, unless you know of a quick fix @jjeffryes)

### CODE REVIEW

**Comment by hoffmabc** [comment]
I'm seeing this weird misalignment I think due to chat.

image

**Comment by morebrownies** [comment]
I have an idea how to resolve the overlay issues. Going to take a stab at it this morning.

**Comment by morebrownies** [comment]
Updates coming soon on this branch. Please hold before reviewing.

**Comment by morebrownies** [comment]
Branch is ready for merge

**Comment by jjeffryes** [comment]
I made a few fixes. Most were older errors that I happened to notice while testing.

One was to remove !important. Do not use !important. That code just needed #ov1 #userPage in front of it to work.

**Pull request merged**
