### PR TITLE
Add @helpdesk to default following list

### PR DESCRIPTION
**Pull request by dsmurrell**
The team behind [duosear.ch](https://duosear.ch) (@dsmurrell and @justin on the OB slack) has been running the @helpdesk node to answer questions people have about OB from the OB client since launch. In order to get visibility we propose that @helpdesk be part of the default followers list. This pull request enacts this.

@helpdesk is provided for free and the support team can be expanded to cover more languages and timezones. We've done some work on the backend to integrate with the popular instant chat service [Intercom](https://www.intercom.io/) so that many support officers can help users on the OB network. Below is a screenshot of a closed conversation:

screen shot 2016-04-27 at 17 16 40

So far, we've had around 350 conversations with OB users through @helpdesk in multiple languages. We've spoken to Washington, Sam, Mike and Brian about this and Brian has suggested that we open it up to community feedback.

### CODE REVIEW

**Comment by morebrownies** [comment]
Side question: How can you make the information that flows through the helpdesk more available to the community? I don't think the conversations need to be fully available to everyone, but do you have plans on publishing trends, common friction points or frequently asked questions so that we (the community) are all aware of the areas that need attention?

**Comment by JustinDrake** [comment]
@morebrownies Absolutely. I have personally filed many (10+) bug reports in reaction to problems we were told on the @helpdesk. See for example #1253, #1247, #1278, #1251, #1287. Daniel has also shared on Slack a map of the world (generated by Intercom) showing where the nodes asking the questions came from. We're happy to share all the stats generated by Intercom.

**Comment by dsmurrell** [comment]
@morebrownies: Intercom lets you build template responses for questions with in-depth answers like 'So, how does moderation work?' or 'How can I keep my store online?'. So far I've made about three or four of these. I've been meaning to trawl through all the closed conversations and annotate common questions/problems over time so that I can better tailor this list of default responses. Working on the search site has delayed this. I've also been linking out to https://openbazaar.zendesk.com/hc/en-us quite a bit. 

We could potentially set up a public github repo and use the issues section to count occurrences of common problems and questions. The problems are more time specific as they will be fixed over time but the questions will highlight more long term changes that might be required or suggest additions to existing information at the zendesk for example. Since you guys also get simple questions on the slack you can help us build this count. What do you think of this idea? We're open to suggestions as well.

**Comment by jjeffryes** [comment]
We're going to provisionally merge this, and see how it goes. 

If there are any issues, we'll revert it.

We may add other nodes to the list in the future, but it will be sparingly and only for good reason.

**Comment by dsmurrell** [comment]
Great, thank you. We'll try not cause any issues. If something comes up that concerns you, please let us know so that we can fix it. Also, if you guys have any suggestions regarding @helpdesk, please suggest away. I'll see if I can get that issue/question tracker up.

**Pull request merged**
