### PR TITLE
Timezone preselect

### PR DESCRIPTION
**Pull request by zhuol**
Use getTimezoneOffset to get offset in minutes, then build string like '(GMT -8:00)', then search by using id contains.
Finally set the radio we find as checked.

But it seems like the timezone value is not really saved finally, so it will be better to make another bug for it.

### CODE REVIEW

**Comment by jjeffryes** [comment]
I don't think the timezone is saved in the API, that will have to be a separate issue.

**Comment by zhuol** [comment]
Right, I can help on timezone saving as well.

And anyone can help review the code before checkin.

**Comment by zhuol** [comment]
BTW, here is the original bug as a reference: https://github.com/OpenBazaar/OpenBazaar-Client/issues/232.
And do we use JIRA or anything else to do development management?

**Comment by jjeffryes** [comment]
We're not using anything except Github for coordinating with contributors right now, though you can look at our issues using Waffle if you want a more friendly way to see everything.

https://waffle.io/OpenBazaar/OpenBazaar-Client

Good work on this PR.

**Pull request merged**
