### PR TITLE
opening server debug log from the context menu

### PR DESCRIPTION
**Pull request by rmisio**
Opening the server debug log via the app context menu.

I believe you will only see the context menu if you are using the binary when created via the installer (via the make process).

### CODE REVIEW

**Comment by jjeffryes** [comment]
@hoffmabc do you want to test this with an installer?

**Comment by jjeffryes** [comment]
@hoffmabc paging Brian...

**Comment by hoffmabc** [comment]
ok will do

**Comment by hoffmabc** [comment]
@rmisio I had to install the open library using npm so can we add that to the package.json?

**Comment by hoffmabc** [comment]
```
"open": "0.0.5",
```

**Comment by rmisio** [comment]
@hoffmabc good catch, I forgot to --save when I installed it. I've updated.

**Pull request merged**
