### PR TITLE
Make messages label unselectable

### PR DESCRIPTION
**Pull request by JustinDrake**
...and fix pointer

### CODE REVIEW

**Comment by gubatron** [comment]
:+1:  LGTM

**Comment by jjeffryes** [comment]
Labels should generally be selectable. What problem does this fix? Would it be better to fix it by changing the element to not be a label?

**Comment by JustinDrake** [comment]
I believe (from memory) that at the HTML level it's a `div`. Call it whatever you want (heading, header, label, title), in this context the text "Messages" should not be selectable.

**Comment by jjeffryes** [comment]
I'll merge this PR, though I think a more general approach would be good, so we're not adding extra properties to a lot of CSS rules.

**Pull request merged**
