### PR TITLE
1450

### PR DESCRIPTION
**Pull request by rmisio**
https://github.com/OpenBazaar/OpenBazaar-Client/issues/1450
- once the chat app is loaded, modals will, by default not cover chat.
- if you would like to completely cover the screen, both nav bar and chat, add the `modal-cover-fullscreen` class to the modal.

I don't think we need the scenario outlined below, but for giggles...
- if you would like to cover chat, but not the nav bar, add both the `modal-cover-fullscreen` & `modal-navOffset` classes, making sure the latter is declared second.

### CODE REVIEW

**Comment by jjeffryes** [comment]
image

The loading graphics got knocked off center.

**Comment by rmisio** [comment]
You mean vertically?

horizontally, it's going to look off-center, especially when the chat is open because it's centered relative to the remaining space. If you close the chat, it will animate over to the right along with the chat app.

**Comment by jjeffryes** [comment]
This is what it's supposed to look like (this is from master)

image

**Comment by rmisio** [comment]
good catch - fixed.

**Pull request merged**
