### PR TITLE
Fix missing fields in store wizard

### PR DESCRIPTION
**Pull request by jjeffryes**

### CODE REVIEW

**Comment by hoffmabc** [comment]
Was this a bad merge that caused this?

**Comment by jjeffryes** [comment]
I don't know. Probably.

**Comment by morebrownies** [comment]
No I dropped those fields on store setup because we ask them in onboarding
now.

**Comment by SamPatt** [comment]
That might work for production but since onboarding doesn't happen each time during testing this means new nodes are unable to set themselves as stores now.

**Comment by jjeffryes** [comment]
They have to be there with the way the form and API currently work.

I can switch things over to fill in missing data from the model, but it's a little more than a quick change. 

This is one of those things that crops up due to the way our APIs don't sync with Backbone. I have a manual sync method I'm using in settings that I need to modularize and refactor into all API calls so filling in missing form data happens automatically.

**Comment by morebrownies** [comment]
The server needs to set a name by default

**Comment by jjeffryes** [comment]
The server doesn't need to set a name, a random name is already being set by the client. 

The issue was the way the storewizard is currently built, only fields that are actually on the page are being passed to the server, and the API needs the name value sent to it. 

I don't see the harm in showing name and description. I think there's a good chance the name and description you put in during onboarding aren't going to be the same ones you want when you set up your store. And if you don't want to change them you don't have to do anything.

**Pull request merged**
