### PR TITLE
User Page form validation

### PR DESCRIPTION
**Pull request by reedrosenbluth**
Added code to validate user input in the settings for the user page. I used a library called [parsley](http://parsleyjs.org/) to do this.

### CODE REVIEW

**Comment by jjeffryes** [comment]
Why not use the HTML5 pattern validation that's already in place on that page?

**Comment by reedrosenbluth** [comment]
@jjeffryes could you possible tell me where that is used? I didn't realize that was already being done.

**Comment by jjeffryes** [comment]
If you look in the settings template, any input that has a pattern attribute is being validated. 

You can see it in the handle, the colors, the libbitcoin server and the refund address.

**Comment by jjeffryes** [comment]
If the pattern doesn't match, there's already code in place to mark the field with an invalid style.

**Comment by reedrosenbluth** [comment]
Disregard my most recent changes, doesn't seem to be working. Fixing now

**Comment by reedrosenbluth** [comment]
Ok, fixed the patterns. seems to be working now

**Pull request merged**
