### PR TITLE
Positioning fixes

### LINKED ISSUE #1565: Notification badge gets cut off
screenshot 2016-05-23 08 24 19

### LINKED ISSUE #1566: Too much spacing underneath the header controls
Currently there is 14px of vertical spacing underneath the header controls and address bar. This can likely be cut in half to 7px or even 5px to free up more vertical space.

screenshot 2016-05-23 08 26 52

### PR DESCRIPTION
**Pull request by jjeffryes**
This reworks all of the various fixed-positioned elements to instead use more intelligent nesting and CSS rules so fixed positioning is no longer required, and elements are automatically positioned based on the size and placement of other elements.

Closes #1565
Closes #1566

### CODE REVIEW

**Comment by rmisio** [comment]
Haven't done thorough testing, so I'm not 100% sure if this is the culprit, but on the latest master the loading modal and page connect modals are covering the top app bar now. AFAIK absolutely nothing is ever supposed to obscure it. There was a whole bug for that purpose and I specifically designed the App bar and updated the css to avoid that scenario.

https://github.com/OpenBazaar/OpenBazaar-Client/issues/1449

**Comment by jjeffryes** [comment]
I forgot to adjust those two. Should be a simple fix.

**Comment by jjeffryes** [comment]
@rmisio can you post a screen shot? This is what they look like to me:

image

image

The position is a little off, but the app bar isn't covered?

**Comment by rmisio** [comment]
image

It's definitely the .page-connect-modal when connecting to a page. Looks like what you styled is when the page-connect-modal is being re-purposed to connect to a server (.page-connect-modal.server-connect) on app start-up.

I thought also the loading modal was doing the same thing, but looks like I was wrong because I can't reproduce it.

**Comment by jjeffryes** [comment]
I found where the issue is, it's just a css problem.

**Pull request merged**
