### PR TITLE
Remove clip attribute that was hiding the map.

### PR DESCRIPTION
**Pull request by jjeffryes**

### CODE REVIEW

**Comment by jjeffryes** [comment]
@rmisio do you remember why the map had a clip with a 0,0,0,0 rectangle?

That was causing the map to disappear as soon as it loaded.

**Comment by rmisio** [comment]
I don't remember. I think I'd need to play around with it to jog my memory. I do recall that I did put it in for some specific reason (something like the map was overhanging it's bounds or something like that).

Anyhow, the fact that this code has been here for months without issue leads me to believe that there is a deeper cause to whatever bug you are working on and removing the clip might be a band-aid at best that may very well introduce another issue.

**Comment by jjeffryes** [comment]
It was changed back in https://github.com/OpenBazaar/OpenBazaar-Client/pull/1541/files#diff-eb1f18c7aba93c4c71bc152bdf4f50bd

I can't find the original reason the clip was added in. 

If I go back to a commit from May 22, this bug still happens. But works fine if the clip is removed, with no negative effects that I've noticed so far.

Either this has been a bug since the clip was added or the Google Maps API changed in a way that broke this.

**Comment by rmisio** [comment]
I'm still seeing the spinner when I have no address.

**Comment by jjeffryes** [comment]
You should still see the spinner for a brief time, and then it will load the default address.

**Comment by jjeffryes** [comment]
Default address as in the generic address that just shows the world map. I thought that was better than a blank screen or a message.

**Comment by rmisio** [comment]
yeah, looks great. I didn't have the latest pull when I wrote that comment.

**Pull request merged**
