### PR TITLE
Remove location from the profile model and REST calls.

### PR DESCRIPTION
**Pull request by jjeffryes**
- this cleans up the location parameter in the Profile API,which isn't used for anything any more.
- it also takes out code passing in the name parameter. The location and name parameters used to be required by the API, but no longer are.
- moderatorSettingsVw.js was completely removed, it was obsoleted by the modal unification PR.

This should only be merged after the server has been updated and both have been thoroughly tested.

### CODE REVIEW

**Comment by JustinDrake** [comment]
I thought it made sense for profiles to have a location. What's the rationale here?

**Comment by jjeffryes** [comment]
The rationale is it's not used for anything, and there's no way to set it.

**Comment by jjeffryes** [comment]
I think the original idea was to enable searching for vendors based on location, but that turned out to not always match where vendors shipped to. 

The same data is in the settings API, if we kept the location parameter in the profile API we'd need to add a way to set it (which is fairly easy), and do something to keep those two pieces of data in sync with each other that isn't confusing to the user.

**Comment by JustinDrake** [comment]
> it's not used for anything

It _is_ used. See for example on Duo Search (e.g. [here](https://duosear.ch/ba2832cca609ce60727c2e8e145fab80fbea07eb)). It's helpful for Duo Search visitors to know the geographical location of the vendor.

**Comment by jjeffryes** [comment]
My point is that information can't be set by the user, so that data isn't going to be accurate.

**Comment by JustinDrake** [comment]
@jjeffryes Fair enough. As you say, it's fairly easy to have code to set it.

**Comment by JustinDrake** [comment]
To confirm, profile `location` is being nuked?

**Comment by jjeffryes** [comment]
That is not confirmed yet, we've just removed code on the client that doesn't do anything.

**Pull request merged**
