### PR TITLE
Add social reminder

### PR DESCRIPTION
**Pull request by jjeffryes**
This will add a social buttons area that appears 10 seconds after the application starts. It has a close button, once that is clicked, it won't appear again.

If this is the user's first time installing the app, the social sharing panel won't appear until after they have paid for their first item.

There is a link in the navigation menu to post to social media, it opens the About modal to the support tab which now has the same sharing links (this duplicates the support link in the navigation menu, I think it's important to have a separate call to action).

The social media post will contain a link to openbazaar.org, and a short blurb about OpenBazaar if the social media platform allows it. The post opens in the browser, and can be changed to whatever the user desires, or canceled. 

image

image

image

image

### CODE REVIEW

**Comment by hoffmabc** [comment]
This is great.

Couple thoughts here though. 

- I think the whole bar is probably too large. It looks a little out of scale with the rest of the UI
- In the menu those links out to social media aren't descriptive enough. Even knowing what they are makes me think that takes users to our official pages for those platforms.

**Comment by jjeffryes** [comment]
@hoffmabc I made adjustments to the language and design, take another look.

**Comment by jjeffryes** [comment]
Re: size, since it only appears once (assuming the user closes it), I think it needs to be a little in your face.

**Comment by morebrownies** [comment]
> This will add a social buttons area that appears 10 seconds after the application starts. 

Does this mean we'll be asking first time users to share while they're in the onboarding process? 🤔

I thought the plan was to display social sharing links once a purchase goes through? I agree with @hoffmabc original point that people are more likely to share when they feel they've accomplished something special (e.g. their first purchase on a decentralized platform!). 

Prompting them 10s after the app launches will lead to a lot of people hiding it as fast as they can so that they can see the content it is covering. Just think about all the random blogs you've landed on that pop a social sharing modal 5s after you land on their site. 
 
> The social sharing links are also in the page nav menu, so someone can easily share news about OpenBazaar after they've dismissed the reminder buttons.

I'm not a big fan of cluttering up the user navigation with 5 social sharing links. That seems pretty extreme. General social sharing links should probably exist within the "Support OpenBazaar" overlay. "Donate or spread the word" seems more appropriate.

**Comment by jjeffryes** [comment]
Lots of updates.

**Pull request merged**
