### PR TITLE
Simple tooltips

### PR DESCRIPTION
**Pull request by mattosborn**
#215. Basic tooltip feature using an attribute. May not cover all use-cases (for example if the tooltip needs more than just text, or needs custom positioning/behaviour).

Not sure how to do the event handling globally with Backbone so the events would need to be added to any view that uses the attribute.

tooltip

pre-commit task failed but not sure if this is a known issue - #221

### CODE REVIEW

**Comment by jjeffryes** [comment]
This should be updated so the events don't need to be set up for each tooltip. 

To do that, wrap your module.exports in a function, so it can be called after render is complete, and have it find all elements with tooltips and assign them the appropriate events. 

The tooltip should also be appended to the element the tooltip is associated with, with a z-index of 1, instead of appended to the body. I don't think the absolute positioning will work in all cases as it's set up now, and wouldn't scroll with buttons when the page scrolls (ie: if used on the user page New Listing button, it should move relative to that button when the page scrolls).

**Comment by mattosborn** [comment]
The tooltip will move with page scroll. Scrolling away also probably means `mouseout` which will hide the tooltip.

I'm not sure what cases absolute positioning wouldn't work here. Both jQuery's `offset` and the absolute positioning on the tooltip element are relative to the page. Nesting the tooltip has it's own issues - it might break spec for some elements, it requires styling on the parent element and it may be affected by the styles of the parent element(s).

As far as the event handling goes - do you mean that each view will import and call the event binding function post-render?

**Comment by jjeffryes** [comment]
In several views, parts of the view scroll independently of the body, if buttons in those views have tooltips the tooltips won't scroll with the buttons if their position is relative to the body. 

You're right that in most cases if you scroll the mouseout will be triggered, but if we put it on a link that was 500px tall, for instance, the tooltip not moving with the triggering element would be an issue. 

Why would nesting require styling on the parent? The parent element's styles might affect tooltips, that's true, they would need to have well-defined rules and sufficient specificity to avoid that. 

We haven't focused on accessibility yet, but to be usable by assistive technology the tooltips should be a child of or next siblings to the element they're triggered by.

Re: event handling, that's the basic idea. It should work like the chosen or cropit libraries, once an instance of the library is created it creates all of the events needed for elements in that view.

**Comment by mattosborn** [comment]
Does the 500px high element-requiring-a-tooltip exist or is that hypothetical?

I'd say hiding it on scroll is a simpler solution for such an edge-case.

The styling I was referring to is the parent needing `position: relative`.

I think this ticket may even be better solved with no javascript at all, using css `:hover`, `attr` and pseudo-elements - see github's tooltip implementation for the top-right buttons in the page header. 

IMO if a very simple solution solves almost all regular cases then it's often better to solve complicated edge-cases separately when they come up rather than try to foresee them.

**Comment by jjeffryes** [comment]
A CSS-only solution would be better, I agree. It should be fairly simple to do something like:

.tooltip {
  position: relative;
}

.tooltip:hover:before{
  content: attr(data-tooltip);
  position: absolute;
  bottom: 10px;
  display: block;
  background: #ddd;
  padding: 20px;
}

The above would fill all the needs for a tooltip without JS. Though we'd want to make it a little fancier looking. 

Putting position: relative on tooltip elements shouldn't be an issue with how most of the app is constructed.

**Comment by jjeffryes** [comment]
I'm closing this PR, since it's out of date and we should go with a all or mostly CSS solution.

**Pull request closed without merging**
