### PR TITLE
Update languagesMd.js Russian localization

### PR DESCRIPTION
**Pull request by Squirrel2020**
Russian language added

### CODE REVIEW

**Comment by hoffmabc** [comment]
@morebrownies @SamPatt can one of you test this real quick for a LGTM?

**Comment by Squirrel2020** [comment]
/u/BitcoinRap here (from reddit). Let me know if more translation/improvement needed, wish I could do more.

**Comment by SamPatt** [comment]
Testing now...

**Comment by SamPatt** [comment]
There were a few places in settings that were untranslated (General, Page, Blocked and Advanced) but everything else looked good.

Obviously I can't speak to the quality of the translation but I give it a LGTM.

**Comment by Squirrel2020** [comment]
Is there any way I could see how it looks using Windows? If you would give some screenshots, I could make translation 100% polished.

**Comment by SamPatt** [comment]
Join our Slack here and we can coordinate: https://openbazaar-slackin-drwasho.herokuapp.com/

**Comment by Squirrel2020** [comment]
> > settings that were untranslated (General, Page, Blocked and Advanced)

How to get these done?

**Comment by SamPatt** [comment]
Notice where English still remains in these screenshots.

I think this is a known issue and the languagesMd.js needs updating, so it would be outside the scope of this pull request.
image

image

**Pull request merged**
