### PR TITLE
Server configuration modal cleanup

### PR DESCRIPTION
**Pull request by morebrownies**
**Changes**
- Cleaned up colors
- Cleaned up spacing
- Cleaned up some language
- Cleaned up typography
- Made retry a button instead of text
- Removed the "Please note settings" modal on save. We have a restore defaults button, so this isn't really needed.
- On save, it now triggers a retry automatically instead of requiring the user to click the retry button.
- On restore, it now triggers a retry automatically instead of requiring the user to click the retry button.

### CODE REVIEW

**Comment by morebrownies** [comment]
@jjeffryes ready for review

**Comment by jjeffryes** [comment]
Wolf, the please note modal is absolutely needed. The restore defaults does not restore your username and password. Clicking that button gives you a blank username and password, so if you didn't write it down you're out of luck.

**Comment by morebrownies** [comment]
Ok, I restored the modal. We'll need to revisit this later as this is going to cause a lot of issues for people that ignore the message.

**Comment by jjeffryes** [comment]
@morebrownies I took out the .start call on restore defaults. What that actually did was just re-run the currently saved credentials, ignoring the URLs that restore defaults had set.

**Pull request merged**
