### PR TITLE
Proof_Read_01_Spanish_version

### PR DESCRIPTION
**Pull request by PolyDeveloper**
Proof-read Spanish version. Moved some lines to match English order.

### CODE REVIEW

**Comment by jjeffryes** [comment]
@PolyDeveloper can you do a new merge on this and resubmit? There appear to be some merge conflicts.

**Comment by PolyDeveloper** [comment]
@jjeffryes Can you please walk me through the process? I noticed there is a message: Only those with write access to this repository can merge pull requests. Could it be  is because I don't have write access? Thanks

**Comment by jjeffryes** [comment]
@PolyDeveloper you should be able to do it with these git commands:

git fetch
git merge master

That will get a copy of the latest master file, and merge it with your current branch. After that check the code to make sure it's working, and the merge didn't break anything.

If you are using the Git desktop app, then do the following:
1. switch your current branch to master
2. click the sync button to update to the latest copy
3. switch back to you patch-1 branch
4. you should now see an option for "Update from master", click it
5. if there are any conflicts, they will be listed in the Changes screen
6. if everything is fine, click sync again (while in your patch-1 branch) to update this PR.

**Comment by PolyDeveloper** [comment]
@jjeffryes Getting the following: 

# Conflicts:

# js/models/languagesMd.js

**Comment by jjeffryes** [comment]
Closed by #356

**Pull request closed without merging**
