### PR TITLE
Transaction modal clean up + misc fixes

### LINKED ISSUE #716: Font Color Issue in Order Details
Unable to set font color in the order details window where it doesn't default to the default font color

screenshot from 2016-02-13 18 29 59

### LINKED ISSUE #744: Black on black
The texts "Type a name..." and "Enter message..." are black on a black background, making them hard to read.

screen shot 2016-02-19 at 19 54 38

### LINKED ISSUE #752: Copyright 2016
In the "Licensing" pane, only 2015 is mentioned in the license.

```
Copyright 2015 OpenBazaar Developers
```

What about 2016?

### LINKED ISSUE #758: Remove mock "Feed" page
In anticipation of the Testnet release on March 1st, should the mock "Feed" page be removed?

screen shot 2016-02-19 at 20 47 32

### PR DESCRIPTION
**Pull request by morebrownies**
**Misc**
- Updated first theme #cc504b
- Add become a moderator to user page nav (@joshj you need to add a route for this to work)
- On the "Create a Wallet" step I now display "Exchange and Wallet" or "Wallet Only" next to each wallet provider
- Add msg to highlight content in textarea
- fixes #716
- fixes #744
- fixes #752
- fixes #758
- Added better box-shadow to modal that is friendly with page themes
- Added box-shadow to maincontainer

**Transactions**
- Cleaned up the spacing in the Summary tab
- Added listing photo in line item in the Summary tab
- Added shipping icon in line item in the Summary tab
- Made Moderator avatar and handle clickable to their page
- Added Order # to the modal header
- Added Order status to the modal header
- Made listing avatar and title clickable to the listing page
- Cleaned up the shipping tab
- Major clean up of the Funds tab
- Added button to funds tab to view transaction on the blockchain
- Hide shipping tab if it is empty
- Re foucs input after sending a dispute message
- Word wrap the contract details to eliminate horz scroll
- Cleaned up the refund button
- Made the confirm order form display in the header instead of the footer (this solves the weirdness with the tabs)
- Cleaned up the typography and spacing in the confirm order form
- If physical item, shipping tab. If digital item, files tab. Only display if order has been confirmed.
- Cleaned up the file tab
- Added rating button to the modal header (if one exists)
- The rating information now slides up when the rating button is clicked
- Contract details now has a header that matches the feedback and confirm header divs
- If no discussion messages, show empty placeholder
- Auto focus the Enter message input when the Discussion tab is clicked
- Fixed the issue with the focus highlight not working on the Discussion tab input

### CODE REVIEW

**Comment by jjeffryes** [comment]
Is the WIP part the route I need to add, or are you still working on parts of it, Mike?

**Comment by morebrownies** [comment]
I'm still working on the feedback section

**Comment by morebrownies** [comment]
You can work in the route whenever you get a chance though

**Comment by morebrownies** [comment]
@jjeffryes might be good to try to get this one merged since it's getting very large. I can start on a fresh branch if you want to start reviewing this one.

**Comment by jjeffryes** [comment]
@morebrownies roger that. I'll work on it after wrapping up a few other things.

**Comment by morebrownies** [comment]
Perfect, I'll be offline for a few hours

**Pull request merged**
