### PR TITLE
Resize icon.png

### PR DESCRIPTION
**Pull request by cpacia**
This icon isn't a square and doesn't render properly when using it as the launcher icon in ubuntu (it gets stretched). I don't know if this will break it on any other OSs. Will need to check.

### CODE REVIEW

**Comment by jjeffryes** [comment]
Will we need to reinstall to test this? It doesn't seem to change the icon at all when I use this branch in Windows.

**Comment by cpacia** [comment]
maybe? it should be 540 x 540. It doesn't change after a git pull?

**Comment by cpacia** [comment]
I'm not sure if this icon is actually used anywhere. But it's the default icon that is used if you install the client as an electron app. 

The packages use that other one with the blue background.

**Comment by jjeffryes** [comment]
Looking more closely, Windows and Mac have dedicated images they use. I can't actually find a place in the code where icon.png is used.

**Pull request merged**
