### PR TITLE
Fixed typo (missing space) in polish language file

### PR DESCRIPTION
**Pull request by JerzySpendel**

### CODE REVIEW

**Comment by jjeffryes** [comment]
@JerzySpendel was this also changed on Transifex? If not, it may get overwritten the next time we update the language files.

**Comment by JerzySpendel** [comment]
I sent join request to polish team.

**Comment by jjeffryes** [comment]
Join request accepted. Let me know when you've updated Transifex.

Normally I pull all the Transifex translations each time we do a release, and update all the languages at once.

**Comment by JerzySpendel** [comment]
Translation on Transifex updated.

**Pull request merged**
