### PR TITLE
No flash on settings

### PR DESCRIPTION
**Pull request by jjeffryes**
- passes a userProfile model to pageNav and settings
- pageNav and settings use that model
- pageNav listens for changes to the profile model, and re-renders on change. This updates the avatar and anything else that changed
- the settings fetch on user and profile was moved to its own function separate from initialize
- when the settings view saves new data, it's models are fetched and the view is re-rendered, this eliminates the flicker.

Known Issue: the re-render is slow, the view can have a noticeable delay in setting the tab state and if a new language was set it is not applied immediately.

### CODE REVIEW

**Comment by SamPatt** [comment]
I tested and don't see a flicker. 

Whenever I save something I do get this displaying now, don't know if that's intentional:

image

**Comment by jjeffryes** [comment]
I'm working on the broken currency search, and I'll improve that save message. I don't think anyone noticed it before because it vanished when the app refreshed.

**Comment by jjeffryes** [comment]
Updated. This should close #297 and close #295

**Comment by hoffmabc** [comment]
Can we merge?

**Comment by jjeffryes** [comment]
This PR has a decent lesson in it, the issue with currency was when list.js was called the subviews inside the list weren't done rendering yet. As far as I know, there's no good way to check that without some fairly convoluted code. 

Instead I changed the list view for currency to just assemble the entire list HTML as strings, which is much, much faster. We may want to apply that in other places too.

**Pull request merged**
